### ISSUE TITLE
add a flag to control console output verbosity

### ISSUE THREAD

**Issue by davybrion** [chucknorris/roundhouse#110]
it would be great if we could pass in a flag to rh.exe to control the verbosity of the output.  For instance, if we could pass in something like --verbosity=minimal and rh.exe would then only show output of scripts that needed to be executed while skipping all output of scripts that can be skipped, it would really make some things easier for us.  The output can grow quite large if you have a large amount of up scripts ;)

**Comment by kitroed** [comment]
:+1:  I'm glad someone read my mind.

**Comment by erikbra** [comment]
This is probably easy if moving from log4net to the Microsoft.Extensions.Logging.ILogger. This is a planned migration (though time is limited)

**Comment by erikbra** [comment]
Commenting on ancient issues here, but, just FYI, grate, our RoundhousE successor/drop-in replacement, has a `--verbosity` flag: https://erikbra.github.io/grate/
