### ISSUE TITLE
[Enhancement] Pass the version number in the command line

### ISSUE THREAD

**Issue by erichexter** [chucknorris/roundhouse#120]
It looks like I have to create some sort of artifact (file) in order to version my db globally. Why cant I just pass this a parameter of the rh.exe ?

**Comment by morganphilo** [comment]
Has this been resolved? I see this in the documentation as --version but in the latest stable version v0.8.6.0 it does not work

**Comment by kunalbuxani** [comment]
I've been setting up a new project wondering why I the --version switch wasn't working. Turns out upgrading to this week's 0.8.7 release fixes the problem.

**Comment by BiggerNoise** [comment]
I'll take that as confirmation that the issue is resolved!
