### ISSUE TITLE
bdddoc.bat Throws an exception during doc generation

### ISSUE THREAD

**Issue by kolupaev** [chucknorris/roundhouse#122]
bdddoc.bat Throws an exception of type ReflectionTypeLoadException.
It seems that it is caused by incompatible target platrofm of bdddoc.console.exe utility.

The problem can be fixed by recompiling bdddoc.console.exe with x86 target.

The exception log is attached as a screenshot.
![image](https://f.cloud.github.com/assets/533414/1196109/9f1af9bc-24a4-11e3-8e62-f2275280c8ac.png)

**Comment by BiggerNoise** [comment]
We're not using bdddoc any longer
