### ISSUE TITLE
RoundhousE.MSBuild dosen't recognize RecoveryMode="Simple"

### ISSUE THREAD

**Issue by liveee** [chucknorris/roundhouse#131]
I'm trying to create a database with RoundhousE.MSBuild with the recovery model "Simple" but I cannot get it to work. First
try:
 <Target Name="CreateDatabaseWithRecoveryModelSimple1">
    
    <Roundhouse
      DatabaseName="TestRH"
      ConnectionString="Data Source=(local);Integrated Security=true;Application Name=RoundhousE;"
	    RepositoryPath="MyRepository"
	    DatabaseType="roundhouse.databases.sqlserver.SqlServerDatabase, roundhouse"
	    OutputPath="$(MSBuildProjectDirectory)\Logs\RoundhousE_runs"
	    Silent="true"
      RecoveryMode="Simple"
      CreateDatabaseCustomScript="custom_db_create.sql"
      />
  </Target>

Then I try:
  <Target Name="CreateDatabaseWithRecoveryModelSimple2">
    
    <Roundhouse
      DatabaseName="TestRH"
      ConnectionString="Data Source=(local);Integrated Security=true;Application Name=RoundhousE;"
	    RepositoryPath="MyRepository"
	    DatabaseType="roundhouse.databases.sqlserver.SqlServerDatabase, roundhouse"
	    OutputPath="$(MSBuildProjectDirectory)\Logs\RoundhousE_runs"
	    Silent="true"
      RecoveryMode="roundhouse.databases.RecoveryMode.Simple"
      CreateDatabaseCustomScript="custom_db_create.sql"
      />
  </Target>

Both results in the following error:
error MSB4030: "Simple" is an invalid value for the "RecoveryMode" parameter of the "Roundhouse" task. The "RecoveryMode" parameter is of type "roundhouse.databases.RecoveryMode".

**Comment by StevenLiekens** [comment]
The problem is that MSBuild does not support converting string input to enum values. The property has to be of type `System.String`. Parsing the enum value requires custom code in the property setter.

**Comment by ferventcoder** [comment]
@StevenLiekens Thanks for the followup.

Ohhh MSBuild... :-1:

**Comment by StevenLiekens** [comment]
I'll send in a pull request.
