### ISSUE TITLE
System.IO.FileLoadException with log4net, Version=1.2.11.0

### ISSUE THREAD

**Issue by khaledm** [chucknorris/roundhouse#152]
Hi, I'm getting this "Could not load file or assembly 'log4net, Version=1.2.11.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)" exception. I understand that roundhouse.lib is using  log4net v1.2.10.0. Not sure why it is seeking to load v1.2.11.0. I've received the same exception with an existing application as well as a throw-away console app. Any suggestions?

**Comment by StevenLiekens** [comment]
I just ran into this. Is there anything I can do to fix it for just my project? I'm trying to use the MSBuild `<Roundhouse>` task in an `AfterBuild` target. The task crashes with a `FileNotFoundException`, no matter what version of log4net I'm using.

**Comment by ChrisMissal** [comment]
Can this be solved with a binding redirect?

**Comment by ferventcoder** [comment]
Unfortunately no, because the key the assembly was signed with changed.

**Comment by ChrisMissal** [comment]
Would this be fixed if we upgrade log4net as part of the 0.8.7 NuGet release?

**Comment by ferventcoder** [comment]
As long as it is fixed in the nuspecs, yes.

**Comment by StevenLiekens** [comment]
Resolved in #245
