### ISSUE TITLE
rh.exe throws System.IO.FileNotFoundException: Could not load file or assembly 'roundhouse.databases.sqlserver' or one of its dependencies

### ISSUE THREAD

**Issue by jafin** [chucknorris/roundhouse#160]
Running Roundhouse v0.8.6.0 (via rh.exe) with the following command.

"C:\BuildAgent\work\8d22666f640fc736\Database..\Tools\Roundhouse\console\rh.exe" --database=STAGING --server=localhost --databaseType=sqlserver --sqlfilesdirectory="STAGING" --noninteractive --warnOnOneTimeScriptChanges

Running RoundhousE v0.8.6.0 against localhost - STAGING
Looking in STAGING for scripts to run.
Setup, Backup, Create/Restore/Drop
Creating STAGING database on localhost server if it doesn't exist.
RoundhousE encountered an error.
System.IO.FileNotFoundException: Could not load file or assembly 'roundhouse.databases.sqlserver' or one of its dependencies. The system can
not find the file specified.
File name: 'roundhouse.databases.sqlserver'
   at System.Reflection.Assembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawl
Mark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)
   at System.Reflection.Assembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlM
ark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)
   at System.Reflection.Assembly.InternalLoad(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forInt
rospection)

Aren't the dll's bundled in the exe?  I can run the command locally using a similar command, this was run on a build server via TeamCity.
Any clues to debug?

**Comment by mortb** [comment]
Please fix the error message.  Very misleading.
