### ISSUE TITLE
C# coding standards

### ISSUE THREAD

**Issue by pvbrakel** [chucknorris/roundhouse#170]
Hi,

Is there a specific reason why the normal c# coding standards are not followed in this project?
Things like:
Namespaces start with lowercase instead of uppercase
Methods start with lowercase and have underscores as separator instead of CamelCase
Interfaces (e.g. ConfigurationPropertyHolder) not starting with a capital I

If we decide to use roundhouse in our project I could refactor that but want to know if that would be appreciated first. 

I am highly fond of the concept of roundhouse and hope my colleagues agree to use it in our project.

Regards,

Pascal

**Comment by ferventcoder** [comment]
@BiggerNoise if you want to grab a similar resharper config - you can grab it from chocolatey/choco - https://github.com/chocolatey/choco/blob/master/src/chocolatey.sln.DotSettings

**Comment by ferventcoder** [comment]
Followed up with #190.
