### ISSUE TITLE
[BUG] The creation of database in SQL 2000 does not work

### ISSUE THREAD

**Issue by pfillion** [chucknorris/roundhouse#176]
In the methode 

```
roundhouse.databases.sqlserver2000.SqlServerDatabase.create_database_script
```

these code doesn't work in SQL 2000.

```
public override string create_database_script()
{
	return string.Format(
		@"
			DECLARE @Created bit
			SET @Created = 0
			IF NOT EXISTS(SELECT * FROM sys.databases WHERE [name] = '{0}')
			BEGIN
				CREATE DATABASE [{0}]
				SET @Created = 1
			END
			SELECT @Created
			",
		database_name);
}
```

We should use **sysdatabase** without the dot.

**Comment by ferventcoder** [comment]
Interesting.

**Comment by ferventcoder** [comment]
Just so we capture exactly where that is https://github.com/chucknorris/roundhouse/blob/master/product/roundhouse.databases.sqlserver2000/SqlServerDatabase.cs#L100

**Comment by pfillion** [comment]
Indeed, it is the right line of code.

**Comment by ferventcoder** [comment]
Would happily take a PR that would change that.

**Comment by sicil1ano** [comment]
Hello! This is one of the changes added with the new versions of Microsoft SQL Server. There were introduced other changes, as explained here (comparison between SQL Server 2000 and SQL Server 2005): http://www.mssqltips.com/sqlservertip/1037/system-information-in-sql-server-2000-vs-sql-server-2005/

I have in my mind a simple fix about that and I have already tested it, in my local SQL Server instance. If it's not a problem for you, I will provide you soon a PR.
