### ISSUE TITLE
Research Framework Upgrade

### ISSUE THREAD

**Issue by ChrisMissal** [chucknorris/roundhouse#178]
See what the upgrade path looks like and create any issues necessary for getting to 4.0 or 4.5. As well as Visual Studio solution version.

**Comment by BiggerNoise** [comment]
Would it make sense to look at upgrading the Visual Studio version at the same time?  

Work doesn't give me Visual Studio any more (I work in *nix land these days), so it would be nice to move this to the 2013 Community Edition.

**Comment by ChrisMissal** [comment]
Yes indeed :+1:

**Comment by ChrisMissal** [comment]
I'll get it running on 2013 Community and get those changes in a PR

**Comment by ChrisMissal** [comment]
Looks like NAnt isn't too happy with the framework changes. Is this also the right time to replace it? @ferventcoder @BiggerNoise

**Comment by ferventcoder** [comment]
Might just need fixes? I may have seen this mentioned in one other place. Any replacement needs to be xplat and provide the same functionality.

**Comment by ChrisMissal** [comment]
Yeah, I'm digging in. I really don't want to have to replace it if I can help it. A small part of me just doesn't want to have to trudge through this much xml. :wink:

**Comment by ChrisMissal** [comment]
Sorry for jumping the gun @ferventcoder @BiggerNoise, ignore my NAnt comments. I was developing in new VM that appears to have some framework inconsistencies.
