### ISSUE TITLE
Considering Roundhouse for a MS SQL 2012 DB hosted @Azure

### ISSUE THREAD

**Issue by jbeckton** [chucknorris/roundhouse#184]
I read the requirements and no mention of support for MS SQL 2012 but have read posts about others running Roundhouse on 2012. I was wondering if there are any known issues with Roundhouse on MS SQL 2012 / Azure?

**Comment by lahma** [comment]
We've been running with SQL Server 2012 and Azure SQL just fine. The limitations come more from the actual supported set of SQL (Azure) than RoundhousE per se. Things gotten better though after the latest update that brought the feature set closer to standard setup of SQL Server.

Just have separate environment to test migrations when using Azure SQL to make sure that you don't do unsupported tricks in your scripts.

**Comment by ChrisMissal** [comment]
@lahma good to hear, can you share some of your experience(s) in the wiki?

**Comment by worldspawn** [comment]
Can anyone confirm roundhouse can create/drop a db when targeting sql azure (not sql server - sql azure)?

**Comment by immeraufdemhund** [comment]
I too am not able to RoundhousE to Azure. I get a error in the connection string, and as far as I can see it appears to happen when `open_admin_connection` is called

**Comment by BiggerNoise** [comment]
I am able to use RH with SQL Azure. I do have to pass --dnc for "do not create".

I don't think that the privileged login that you get with SQL Azure is privileged enough to create databases. 

The rest of RH seems to work pretty well though.

**Comment by BiggerNoise** [comment]
@worldspawn I wasn't using SQL Azure when you asked your question last year, but now I can say pretty certainly that you cannot use RH to create or drop databases with SQL Azure, the connection doesn't have necessary privileges.

**Comment by worldspawn** [comment]
Hi guys, you definitely can use roundhouse for all your azure shenanigans.

You need to use an admin connection string (for the elevated privileges) as well as provide a customised create script. Heres some powershell i wrote to wrap this up for me.

_createazure.sql_
```
USE master
DECLARE @Created bit
SET @Created = 0

IF NOT EXISTS(SELECT * FROM sys.databases WHERE [name] = '{{DatabaseName}}')
BEGIN
        Set @Created = 1

        CREATE DATABASE {{DatabaseName}}
		( MAXSIZE = 500 MB, EDITION = 'standard', SERVICE_OBJECTIVE = 'S1' ) ;  

END 

SELECT @Created
```

_database.ps1_
```
param(
	[string]$appName = "portal", [string]$dbName = "RateItNowDb", [string]$connStr = "Data Source=(local);Initial Catalog=$dbName;Integrated Security=SSPI", [string]$adminConnStr = "Data Source=(local);Integrated Security=SSPI", [string]$env = "LOCAL", [switch]$recreate = $false
)

if ($recreate -eq $true -and $env -eq "prod") {
    Write-Host "Cannot drop production"
    exit
}

$rh = ".\rh\rh.exe"

#Options - https://github.com/chucknorris/roundhouse/wiki/ConfigurationOptions
if ($recreate -eq $true) {    
    & $rh --drop -d $dbName -c $connStr -csa $adminConnStr --env $env -f ".\$appName\" --silent -t
    Write-Host "Waiting 15 seconds... because Azure"
    Start-Sleep -s 15
}

if ($appName -eq "portal" -and $env:AZURE -eq "TRUE") {
    & $rh -d $dbName -c $connStr -csa $adminConnStr --env $env -f ".\$appName\" --silent -t --ct 1800 --cds .\createazure.sql
}
else {
    & $rh -d $dbName -c $connStr -csa $adminConnStr --env $env -f ".\$appName\" --silent -t --ct 1800
}

if ($LASTEXITCODE -ne 0) {
    exit 1
}
```

Theres an environment variable (env:AZURE) it checks to use the azure create script. Hope this helps.

**Comment by BiggerNoise** [comment]
Thanks @worldspawn! That's good to know.

Can you speak to what your custom create does differently than stock RH create? It's been a long time since I have been in the RH code.

**Comment by worldspawn** [comment]
Addendum: if you open the server (not the database) in azure in the overview you will see a heading "Server admin" with the username underneath. This is the credential you should use for your admin connection string. If you dont know the password you can reset it from there.

![image](https://user-images.githubusercontent.com/819581/26908226-9c748e12-4c3c-11e7-8519-9c450d74bbdf.png)

**Comment by worldspawn** [comment]
Its sets the edition and serviceobjective properties. Its been a while since I viewed the error returned from the default so I cant say more on it. This is the default create code:

```
public override string create_database_script()
        {
            return string.Format(
                @"      DECLARE @Created bit
                        SET @Created = 0
                        IF NOT EXISTS(SELECT * FROM sys.databases WHERE [name] = '{0}') 
                         BEGIN 
                            CREATE DATABASE [{0}] 
                            SET @Created = 1
                         END
                        SELECT @Created 
                        ",
                database_name);

            //                            ALTER DATABASE [{0}] MODIFY FILE ( NAME = N'{0}', FILEGROWTH = 10240KB )
        }
```

https://github.com/chucknorris/roundhouse/blob/master/product/roundhouse.databases.sqlserver/SqlServerDatabase.cs

**Comment by BiggerNoise** [comment]
Thanks

**Comment by erikbra** [comment]
I did try to solve this a couple of years ago, with the issue #182 , however the test framework at the time was so outdated that I couldn't actually compile the solution and run the tests on a modern Visual Studio. My pull request was not accepted, because I had made too many non-related changes. That is fair, however, it is difficult to keep a sensible development pace when not keeping tools, etc up-to-date. I am not criticising anyone, just pointing out the fact. 

Unfortunately, I haven't had enough time to contribute more to RoundHouse, so we have just been using a build off the build server of this commit. Not ideal, and I know not anyone else than me can benefit from it. I should take my time and try to make the pull request once again from the latest version of RoundhousE. 

FYI, this adds support for not needing to have a server-level admin: https://github.com/chucknorris/roundhouse/pull/182/commits/fae70577087de4493896d28db5dcecafdbf6bbcc

**Comment by ferventcoder** [comment]
@erikbra it's a fair assessment - RH has reached a certain point and it has not have any active maintainers for awhile. While unfortunate, we've been looking for folks who could pick this is and carry it forward. 

This looked good -https://github.com/chucknorris/roundhouse/pull/187/files (your superseding PR), but there was a feedback request and we never heard back. See https://github.com/chucknorris/roundhouse/pull/187#r32056192 for details.

**Comment by erikbra** [comment]
Just a note on the comment by @worldspawn, this is no longer necessary if you create the SQL Azure DB yourself otherwise (as you typically do, using an ARM template or something), you can now pass the `--dna` for "Do not alter", and then you don't need the admin connection anymore. Yes, this should be properly documented. Where?

**Comment by erikbra** [comment]
Closing this one - RH works with SQL Azure now.
