### ISSUE TITLE
Permissions not being granted

### ISSUE THREAD

**Issue by ashic** [chucknorris/roundhouse#188]
Hi,
I've got a weird issue around granting permissions. It seems that the same roundhouse scripts targeting my local machine work fine (i.e. db created, permissions assigned), but when targeting some remote machines, the db and tables are created, but no permissions are assigned. I've treble checked that Roundhouse IS running the permissions files, and it's all green (no errors) - the permissions simply aren't granted.

If I copy - paste the script into mgmt studio running under the same account (Integrated Security), then the permissions ARE assigned. If I run the file from sqlcmd targeting the remote databases, the permissions ARE granted.

At this point, my guess is that some policy on the remote dbs prevent applications from updating permissions. Otherwise, using the same credentials and connection strings, I'd expect the permissions to work.

Does anybody have any ideas as to why mgmt studio + sqlcmd would work, but roundhouse wouldn't?

**Comment by ferventcoder** [comment]
Never ran into this issue and we extensively used the permissions against a non-local db.

**Comment by ferventcoder** [comment]
Out of curiosity, there is a scripts table - are they in there? And do you have an example of a script you can share (email me directly if it needs to stay private)?

**Comment by ferventcoder** [comment]
After reviewing the scripts, I wonder if it is a permissions issue of the process running rh.exe - are you running it? Or is this some automated process? Since it is being run by integrated security, that's what I'm wonderting.

**Comment by ashic** [comment]
I'm running the scripts using my domain account. If I use sqlcmd and point to the files, they work (after replacing {{DatabaseName}}). Also, logging into mgmt studio with the same credentials and running the scripts work as well.

**Comment by ashic** [comment]
Please ignore. Turned out to be a transaction rollback. Grrrr....
