### ISSUE TITLE
Tag Releases and Upload Binaries

### ISSUE THREAD

**Issue by ChrisMissal** [chucknorris/roundhouse#205]
- [ ] v0.0.0.54
- [ ] v0.0.0.59
- [ ] v0.0.0.60
- [ ] v0.0.0.67
- [ ] v0.0.0.69
- [ ] v0.0.0.73
- [ ] v0.0.0.74
- [ ] v0.0.0.83
- [ ] v0.0.0.85
- [ ] v0.0.0.86
- [ ] v0.2.0.97
- [ ] v0.2.0.101
- [ ] v0.2.0.109
- [ ] v0.2.0.117
- [ ] v0.2.0.131
- [ ] v0.2.0.144
- [ ] v0.2.0.148
- [ ] v0.2.0.150
- [ ] v0.2.0.175
- [ ] v0.2.0.188
- [ ] v0.5.0.188
- [ ] v0.7.0.276
- [ ] v0.7.0.281
- [ ] v0.8.0.300
- [ ] v0.8.5.0
- [ ] v0.8.6.0

**Comment by ferventcoder** [comment]
One small edit, drop the "v" if possible in the tags.

**Comment by BiggerNoise** [comment]
@ferventcoder, @ChrisMissal - Are we still planning to do this, or are we going to just have binaries for 0.8.8 onward?

**Comment by erikbra** [comment]
Tags are always nice, to be able to check out a previous release, imho.

**Comment by BiggerNoise** [comment]
I don't doubt they're nice. I guess my real question is, does anyone care about this enough to actually do the work? 

If not, I want to close it.

**Comment by ferventcoder** [comment]
I can do some of this, mostly the tags

**Comment by ferventcoder** [comment]
Previous releases are out for folks so I think releases forward we can do.

**Comment by erikbra** [comment]
Is the task here to add tags for all *previous* releases? Or just going forward?

**Comment by ferventcoder** [comment]
All previous. Scouring the git logs to determine when the release happened. Spelunking is kind of fun sometimes.

**Comment by erikbra** [comment]
Closing this. Although it would be 'nice', I don't see the point in using time on it now.
