### ISSUE TITLE
Clean up SQL Server Specific code

### ISSUE THREAD

**Issue by ChrisMissal** [chucknorris/roundhouse#212]
Some SQL Server specific code has gotten into the `AdoNetDatabase` class and needs to be moved to `SqlServerDatabase` to be corrected.

**Comment by drusellers** [comment]
:+1: I'm currently trying to get RH working on mono for postgres. so this would be much appreciated. :)

**Comment by erikbra** [comment]
@ChrisMissal or @drusellers do you have any more info on what needs to be (re)moved? Maybe you could write a failing test, or otherwise help us investigate? Thanks.

**Comment by drusellers** [comment]
@erikbra i took a quick stroll through the code and I'm not seeing anything at the moment. I'm good to close in @ChrisMissal  is.

**Comment by erikbra** [comment]
Closing this one, then, as we are at least two people who can't see the SQL server specific code here anymore.
