### ISSUE TITLE
Baseline seemingly ignored

### ISSUE THREAD

**Issue by Jonathan-Turner** [chucknorris/roundhouse#213]
Good afternoon,

I am in the process of implementing database deployment via Roundhouse at my current employer (yay). They have several legacy databases. We have scripted out the appropriate .sql files and assorted them to the various folders (up, sprocs) etc as you'd expect.

I saw the --baseline command line flag and my reading of this is that RH will create ScriptsRun entries for each of the files it finds but not actually run those files, in essence allowing me to "catch up" the roundhouse implementation in the database. We would then continue to add / modify scripts as normal from that point on.

However, running with --baseline doesnt seem to affect anything. I error on my first script in UP, where it complains that suchandsuch schema already exists. Its clearly running the file.

Am I reading the intent of --baseline wrong?

Thanks for any insight you can give.

**Comment by ferventcoder** [comment]
It's there, but it is a switch that was not implemented. We did just implement it for release in 0.8.7 with #111

**Comment by ferventcoder** [comment]
You can get to the latest RH builds at http://teamcity.codebetter.com/viewType.html?buildTypeId=bt210

**Comment by Jonathan-Turner** [comment]
Thanks man I was just coming back to ask you where to find it. Appreciate your help sir.
