### ISSUE TITLE
WarnOnOneTimeScriptChanges does not fail when set to false

### ISSUE THREAD

**Issue by dquser** [chucknorris/roundhouse#219]
I set WarnOnOneTimeScriptChanges to false and I expected it to fail when a one-time script is modified. Instead, I get the message "script.sql is a one time script that has changed since it was run." In addition to that, the script runs anyways and Roundhouse continues executing the other scripts.

I was expecting it to fail.

By the way, if I set WarnOnOneTimeScriptChanges to true, I get the exact same behavior.

**Comment by ferventcoder** [comment]
@dquser it ***used** to work. What version of RoundhousE do you have?

**Comment by dquser** [comment]
Actually, I believe I have a solution. Given that it's a switch, it's mere presence would mean "on". So I will just remove it and try again and let you know. Thank You!

**Comment by ferventcoder** [comment]
@dquser yes, you don't pass it unless you want it to be on.
