### ISSUE TITLE
Fix onetime script hash if script is modified

### ISSUE THREAD

**Issue by lukemcgregor** [chucknorris/roundhouse#226]
The `--warnononetimescriptchanges` option re-runs one time scripts which have been modified and updates the hash.

Modifying existing scripts sucks but sometimes its necessary. 

It would be good if as well as warning and re-running there was an option to warn and not re-run but fix the hash anyway.

A good example of where I want this is where we are introducing RH to an existing DB and have generated a from zero script (so we can create new instances of the DB), but later we want to exclude part of that schema or add in some extra static data that was in the original database. We wouldn't want to re-run this script on the original database so we just want to ignore the hash failure for that script.

This is essentially the fixit script for a change to a --baseline script

I suggest the option could be called:
    
    --warnandignoreononetimescriptchanges

**Comment by ferventcoder** [comment]
I'm not sold on the name. I'd almost prefer a new option, I think we may have discussed this previously.

**Comment by ferventcoder** [comment]
For clarity, prefer a new option that complements the warnononetimescriptchanges that allows it to fix the hash.

**Comment by lukemcgregor** [comment]
Its kind of like --warnononetimescriptchanges --baseline except it will only re-baseline things that have changed. Any suggestions on a name that suggests this?

**Comment by tilakbhanu** [comment]
I want to re-baseline indexes script (removing use statement in the script). folder using warnandignoreononetimescriptchanges - does it apply?

**Comment by BiggerNoise** [comment]
@tilakbhanu - I don't think that indexes is a one time folder. So, changes to files in that folder will result in them being re-run.

Of course, this requires that your index file is re-runnable.

I believe that I wrote all of my index scripts such that they would drop the index if it existed, then create it.
