### ISSUE TITLE
Publish NuGet packages

### ISSUE THREAD

**Issue by amacal** [chucknorris/roundhouse#241]
The development cycle is very slow and it the current 0.8.6 version has a bug fixed in issue #206 without workaround. I propose to reduce the scope of the 0.8.7 and create the next release or just often enough create prereleases.

**Comment by ferventcoder** [comment]
@ChrisMissal @drusellers thoughts?

**Comment by drusellers** [comment]
i have no problem with releasing. I'd love to finish out (with @ferventcoder ) the mono fixes and get those released as well - but after we get this current release so we can solve some pain.

**Comment by BiggerNoise** [comment]
0.8.7 has been released; 0.8.8 coming shortly
