### ISSUE TITLE
Unit and integration tests - are they used?

### ISSUE THREAD

**Issue by erikbra** [chucknorris/roundhouse#243]
I have a WIP issue #187, but I would love to be able to run some tests before trying to submit a pull request again. However, tooling for MBUnit is far from ideal. I have not been able to find any plugin that works with VS2015, neither for Resharper or pure runner (TestDriven.Net doesn't seem to work anymore). I don't feel very comfortable not being able to run tests. 

1) Are there any MBUnit runners for VIsual Studio 2015? Or command-line/gui?
2) Would it be an idea to consider moving to a more actively developed test framework, e.g. NUnit, XUnit, MSTest, etc?

I really love RoundhousE, and use it in production with success. I just fear depending on dying(?) frameworks could be a hindrance going forward. Opinions or tips?

**Comment by ferventcoder** [comment]
We were looking at one point at converting all of the tests over to NUnit/TinySpec framework. If you are interested, look at DropKick or Chocolatey's tests and you can see how it is somewhat similar with less magic involved. 

You can run the tests from the command line by typing `test` and `test all`

**Comment by erikbra** [comment]
If I should have any hope on working a bit on RoundhousE, I need a working test suite that can be run in Visual Studio. Do you know, @ferventcoder, if there are any active efforts to convert to a more actively developed testing framework, or should I just have a go at it? I have experience from day-job with xUnit and e.g. FluentAssertions, and no experience with TinySpec. Do you have a strong opinion on this? I just feel that if more "main-line" test and assert frameworks are not adopted, it will be difficult to get new contributors to engage. But, I might of course be biased from my current experience.

Do you have any strong opinions against converting to e.g. xUnit or NUnit? I havent looked at all the tests, and I think MBUnit is way more BDD-style than these two, but with the help of e.g. FluentAssertions, maybe we could make the porting not too intrusive.

**Comment by ferventcoder** [comment]
@erikbra Chocolatey's test suite has that ability - and also the documentation is getting more comprehensive, see https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#debugging--testing

**Comment by erikbra** [comment]
I made a pull request where I converted all the MBUnit tests to xUnit. Could you please have a look at it when you have some time?

"Converted all tests from MBUnit to xUnit" #271

**Comment by ferventcoder** [comment]
NUnit was the hope here.

**Comment by erikbra** [comment]
Yes, sorry about that. I'll convert to NUnit if you prefer, but I couldn't find a good substitute for the `Observation` attribute in NUnit. Are you aware of any?

**Comment by ferventcoder** [comment]
I am going to defer the decision on the switch to @biggernoise. As far as substitutes - did you spend any time looking over choco's source code? It's very similar to what you achieved and tinyspec os what allows for fact/observation attributes as an inheritor of the test attribute.

**Comment by erikbra** [comment]
Sorry, I haven't had the chance to look through choco's source code in detail yet. I will, though. And, if it's a point to keep them similar, I can try to align the changes in RoundhousE with the looks of choco. Is master the best branch to look at?

**Comment by BiggerNoise** [comment]
Thank you for the P/R on this
