### ISSUE TITLE
Enforce a particular encoding

### ISSUE THREAD

**Issue by StevenLiekens** [chucknorris/roundhouse#255]
I get so annoyed when my text editor saves a script in some weird encoding (UCS-2 LE + BOM to give an example). It would be so nice if RH would refuse to run such scripts. All scripts should be UTF-8 without BOM. Changing the encoding after the script has been run is a PITA.

**Comment by StevenLiekens** [comment]
Currently, if a SQL script file does not contain a BOM (which is not required or even recommeded for UTF8) the code falls back to `Encoding.Default`. Sounds good? It's not. This is the insane part: **the default encoding depends on operating system settings**.

https://msdn.microsoft.com/en-us/library/system.text.encoding.default(v=vs.110).aspx
> Different computers can use different encodings as the default, and the default encoding can even change on a single computer. Therefore, data streamed from one computer to another or even retrieved at different times on the same computer might be translated incorrectly. In addition, the encoding returned by the Default property uses best-fit fallback to map unsupported characters to characters supported by the code page. For these two reasons, using the default encoding is generally not recommended. To ensure that encoded bytes are decoded properly, you should use a Unicode encoding, such as UTF8Encoding or UnicodeEncoding, with a preamble. Another option is to use a higher-level protocol to ensure that the same format is used for encoding and decoding.

This is the relevant code: 
https://github.com/chucknorris/roundhouse/blob/master/product/roundhouse/infrastructure/filesystem/DotNetFileSystemAccess.cs#L68-L89

**Comment by ThomasMldr** [comment]
Due to this issue "m³" was changed to "mÂ³" when run through roundhouse, if my file was saved as UTF8 without BOM.. Why would you check on the BOM to check the encoding?

**Comment by sfkleach** [comment]
Bump.

**Comment by Liwoj** [comment]
Using BOM for detecting encoding is right thing to do. Using Encoding.Default when BOM is missing is not. Use UTF-8 instead...

**Comment by Liwoj** [comment]
Commit https://github.com/chucknorris/roundhouse/commit/81a3fdaabf942c7780d5ce95afdf0aa8179090e4 adds new parameter for encoding.

I have 2 problem with the implementation:
1) If specified, it makes RH to completely skip BOM detection. This has a potential to break some older scripts. Wouldn't be better to try detect BOM 1st and use encoding passed on command line only if BOM is not there (instead of Encoding.Default) ?

2) It uses encoding name. It means you can't use UTF-8 encoding without BOM (there is no name for any utf encoding without BOM in .NET)

**Comment by Liwoj** [comment]
Yep, sounds good. I would do one small change in point 3. - "If no BOM or flag, use UTF-8 **without BOM**". I have three reasons for that:

- UTF-8 (with BOM) is already covered by step 1. 
- UTF-8 without BOM is very common
- Unicode Standard permits the BOM in UTF-8, but does not require or **recommend its use**

As for the flag enhancement. There is no standard name for utf-8 without BOM (as far as i know). That means some proprietary extension is needed - for example appending "_NOBOM" to standard encoding name. 
Also i'm not sure about usefulness of doing same thing for other encodings (utf-16\32)....

Ideas?

**Comment by BiggerNoise** [comment]
Thank you for the feedback, encodings are not my strong suit, so I need to take direction from folks that have more in depth knowledge.

I agree with the UTF-8 Without BOM

On the flag I am fine with UTF8_NOBOM. We can add others if the need materializes.

I don't suppose you would be willing to submit a P/R for this would you?

**Comment by Liwoj** [comment]
I should be able to find some time to implement this in a few days. That should also give some time to others to comment (@icedtoast)

I would also change current parameter name to more reflect new behavior. Something like "defaultencoding" or "fallbackencoding" should work...

**Comment by BiggerNoise** [comment]
OK. Thank you very much. With that P/R and a couple of others that are still left to merge, I think we can bake the next release.

BTW - I agree with your parameter name suggestion, of the two, I think I prefer "defaultencoding" but I will accept either.

**Comment by BiggerNoise** [comment]
I believe that #283 and release 0.8.8 address this one.
