### ISSUE TITLE
Initialialize TLS 1.x support

### ISSUE THREAD

**Issue by hirenhirani** [chucknorris/roundhouse#258]
We have a pull request pending to fix this very issue after hardening our environments for PCI compliance and were wondering if it can be accepted and merged into the main code base rather than us forking and adding a maintenance headache to keep repo's up to date with any future changes made in the main repo. We would be grateful to hear any counter arguments if any?

Thanks 

https://github.com/chucknorris/roundhouse/pull/253

**Comment by BiggerNoise** [comment]
Merged P/R
