### ISSUE TITLE
please update package in chocolatey repository

### ISSUE THREAD

**Issue by otakusid** [chucknorris/roundhouse#259]
Looks like development of **roundhouse** is more live than dead, so it would be cool to see updates in the **chocolatey** repository for such useful tool

https://chocolatey.org/packages/roundhouse

**Comment by hmvs** [comment]
Could you please also update GEM package. Because there is an old version which has compatibility issues with mono.

**Comment by BiggerNoise** [comment]
I am trying to get it updated, but I need to resolve some moderation issues first (https://github.com/chucknorris/roundhouse/issues/274). Once I manage that, choco will be up to date.

I'm going to close this issue as it is contained within the other.
