### ISSUE TITLE
TableCreationScripts for PostgreSQL do not handle schema name properly

### ISSUE THREAD

**Issue by tsaluszewski** [chucknorris/roundhouse#260]
I am using Roundhouse with postgreSQL 9.3. The tool is great (thanks guys!), but I cannot configure roundhouse to create its tables in the custom schema, i.e. export. If I specify the schema switch (/sc=export) it effecivelly creates the table with the prefix in the default schema, rather than in the schema itself. Effectivelly I have tables named like export_scriptsrun, export_scriptsrunerrors, export_version. I presume there is a bug in the https://github.com/chucknorris/roundhouse/blob/master/product/roundhouse.databases.postgresql/TableCreationScripts.cs as the CreateRoundHouseVersionTable('{0}_{1}') uses "_" instead of "."?

**Comment by BiggerNoise** [comment]
I merged the associated P/R, so I am closing this.

**Comment by tsaluszewski** [comment]
Thank you very much!
