### ISSUE TITLE
NuGet package roundhouse.lib is not the latest.

### ISSUE THREAD

**Issue by greg-murray-volusion** [chucknorris/roundhouse#265]
It still has a reference to 'log4net.1.2.10', which was fixed on April 1, 2016.

https://github.com/chucknorris/roundhouse/blob/master/nuget/roundhouse.lib/roundhouse.lib.nuspec

Thanks

**Comment by BiggerNoise** [comment]
With the recent flurry of P/R merging, it appears that this has been addressed. Please reopen if it is still an issue.
