### ISSUE TITLE
Running rh.exe - This application could not be started

### ISSUE THREAD

**Issue by propellor** [chucknorris/roundhouse#269]
Hi,

Trying to run rh.exe for the first time on Windows 10.  Has worked fine on 7 in the past.  When I run rh.exe /? from the command line, I get "This application could not be started.  Do you want to view information about this issue?"  Of course I do, so I click Yes and see this URL.

https://support.microsoft.com/en-us/help/2715633/shim-errors-for-the-.net-framework-version-and-platform-support

> This application could not be started.
> 
> The app is not configured in a way that makes it possible to determine the appropriate version of the .NET Framework runtime. The corresponding shim code is SHIM_NOVERSION_FOUND.
> 
> You can't fix the configuration problem yourself. Contact the app vendor to resolve the issue. 

Any idea if this is my issue or roundhouse?

Thanks so very much!

**Comment by ferventcoder** [comment]
You can enable .NET framework 3.5 in Programs and Features. However it may be best to set a rh.exe.config to allow it to run in .NET 4.x.

**Comment by propellor** [comment]
I have .net 3.5 enabled.  Checked that before posting as it was referenced.  I'll check out the rh.exe.config if I can figure out where choco installed roundhouse :)

**Comment by propellor** [comment]
Figured out the issue - had a copy of rh.exe sitting somewhere else which was being picked up and run.  Removed that and the new one is running fine.  Thanks for the awesome tool.
