### ISSUE TITLE
Failing Chocolatey Moderation

### ISSUE THREAD

**Issue by BiggerNoise** [chucknorris/roundhouse#274]
I'm trying to clear some of the old backlog. 0.8.7 has been released, but is failing moderation on the Chocolatey site. Specific issues are:

Please remove these files from your package:

content\ReadMe.RoundhousE.txt
docs\GettingStarted.docx
docs\LICENSE
docs\NOTICE

Because you have included binaries, you need to include tools\LICENSE.txt and tools\VERIFICATION.txt (see choco new for examples)

I have assigned @ferventcoder, but anyone can make the requested changes.

I'm going to pull in some of the outstanding pull requests to make an 0.8.8 and I'd like to release this to choclatey at the same time.

**Comment by ferventcoder** [comment]
That's interesting but I get why those things would be pulled out.

**Comment by erikbra** [comment]
Are we OK with calling this "done" for now, @BiggerNoise, @ferventcoder ? I think what is output from AppVeyor now in master should be approved in Chocolatey? I'm marking this as 0.9.0, supposing that you're OK with closing it. Please scream out if you disagree :)

**Comment by BiggerNoise** [comment]
It should close with the 0.9.0 release. I want to hold off closing it for real until we actually get through the moderation process.

**Comment by BiggerNoise** [comment]
The 0.9.0 release has passed the automated chocolatey automation. I'll close this once I can install 0.9.0 from choco

**Comment by ferventcoder** [comment]
Don't forget to edit that nuspec to not just have me as the software author. It's more folks, but you both definitely should be listed in there.

**Comment by ferventcoder** [comment]
For next time.

**Comment by BiggerNoise** [comment]
['nuff said](https://chocolatey.org/packages/roundhouse/0.9.0)
