### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by jbogard** [chucknorris/roundhouse#276]
Wanted to use the RH library in a .NET Core project but no dice :(

**Comment by BiggerNoise** [comment]
I am curious if you want to use RH as a library or if you just wanted a .NET Core executable?

At any rate, my (rough) plan is:
- Merge as many P/Rs as I can and release 0.8.8
- Modernize the dependencies and tools for release 0.9.0 (that would be when I could look at .NET Core)

No timelines, but hopefully, the gap between 0.8.7 and 0.8.8 will be smaller than the one between 0.8.6 and 0.8.7.

**Comment by jbogard** [comment]
As a library, to be able to execute as part of running a suite of tests.

Dunno about the .net core side but a next step would be a .NET CLI tool.

**Comment by lahma** [comment]
There might be some work to do, here's the [analysis for .NET Core](https://icanhasdot.net/result?github=chucknorris~2Froundhouse). Looks like Fluent NHibernate and NHibernate are the ones that require most love at the moment.

**Comment by jbogard** [comment]
What is RH using FNH/NH for?

**Comment by NightOwl888** [comment]
> As a library, to be able to execute as part of running a suite of tests.

In that case, it might make sense to target [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) rather than .NET Core, which gives you better platform support. .NET Standard applies only to libraries, but makes them possible to share between .NET Framework and .NET Core (which ultimately cuts down on platforms you need to target).

**Comment by jbogard** [comment]
Yep! Just did this myself with my Respawn and BulkWriter projects, targeting netstandard1.2 I believe.

**Comment by BiggerNoise** [comment]
@lahma Thanks for that information
@jbogard It's used to create and populate the tables in the roundhouse schema (scripts_run, etc.)

The use of NH is so limited in the lib, that I would almost lean towards not using an ORM at all. It's been a while since I have been deep into that area of the code, but that seems like a great way to lop off a dependency.

I'll stress that I want to get some of the P/R's merged an get a 0.8.8 out before I start wrenching in this area. And life seems to have other plans for me apart from doing Roundhouse.

**Comment by jbogard** [comment]
Is that how RH provides support for different DBs? Lets NH handle that?

**Comment by BiggerNoise** [comment]
I don't think NH is that involved in running the user scripts (other than as a pass through to get the connection).

We definitely use it for managing the scripts_run and other tables in the roundhouse schema.

**Comment by lahma** [comment]
The core DB update logic being quite simple, I'd argue a somewhat more simpler approach could work updating the migration information. In Quartz.NET I'm using quite [simple metadata](https://github.com/quartznet/quartznet/blob/master/src/Quartz/Impl/AdoJobStore/Common/dbproviders.properties) for each database to figure out how to do CRUD. 

Might be worthwhile to think if switching to more lightweight like [Dapper](https://github.com/StackExchange/Dapper) (insert your favorite ORM alternative here)  would be an alternative. As said, the actual maintenance of migration state tables isn't too complicated.

**Comment by jbogard** [comment]
Cool, is this something that you're looking for help on?

**Comment by BiggerNoise** [comment]
It would be very nice to have help on this.

I would ask that you hold off for another week or two. I am trying to clear the P/R backlog and I'm seeing kdiff in my dreams.

**Comment by erikbra** [comment]
We're getting closer to this given #285. I don't think all database providers will work with .NETStandard, but we can always multi-target. It would be nice to have `rh.exe` with e.g. just SQLServer running on Linux too, using dotnet core (as SQL Server runs on Linux now). 

I think lots of dependencies can be removed, but I haven't looked at it thoroughly enough yet.

**Comment by erikbra** [comment]
@jbogard: We have an issue with porting to netstandard2.0 (see pull request)

**Comment by extofer** [comment]
looking for an update on .NET Core support. Is there an ETA, or is there a light version that can be supported?

**Comment by BiggerNoise** [comment]
There is no ETA. 

Core support requires significant work to eliminate a dependency and we're still figuring out how to manage that. Unfortunately, the dependency is pretty fundamental to RH, so a light version wouldn't be able to help.

Sorry that I don't have better news.

**Comment by jbogard** [comment]
What are the fundamental pieces that the dependency has? Is it just that it can handle DML/DDL for anything NHibernate supports for the 3 tables that RH uses?

**Comment by BiggerNoise** [comment]
In a nutshell. The conversation is over in #294.

**Comment by erikbra** [comment]
This is basically solved, and fixed and released in release 1.0.0
