### ISSUE TITLE
Separate nuget packages for rh.exe and MSBuild tasks/dll?

### ISSUE THREAD

**Issue by erikbra** [chucknorris/roundhouse#286]
Just thought of this, working on #285. The nuget for rh.exe is just for Chocolatey, right? There's nothing stopping us from building a nuget package for the dev experience as well. I'm not using it, but @jbogard mentions that he uses it from integration tests in #276 . I suppose you don't need the ILMerged rh.exe for this, just some of the DLLs? Or am I wrong?

**Comment by ferventcoder** [comment]
It's done a different way. All done in the uc builds.

**Comment by ferventcoder** [comment]
I know, not fun to read the NAnt system.

**Comment by ferventcoder** [comment]
Check here for all of the build customizations - https://github.com/chucknorris/roundhouse/tree/master/build.custom

* MSBuild - https://github.com/chucknorris/roundhouse/blob/master/build.custom/ilmergeMSBuild.build
* DLL - https://github.com/chucknorris/roundhouse/blob/master/build.custom/ilmergeDLL.build
* Roundhouse Lib and MSBuild NuGet packages are setup with https://github.com/chucknorris/roundhouse/blob/master/build.custom/nugetPrepare.post.step

**Comment by ferventcoder** [comment]
https://www.nuget.org/packages/?q=roundhouse there are like 4 that come out of this source during the build.

**Comment by erikbra** [comment]
Aaah. I see I have missed a few in #285. Must fix.

**Comment by erikbra** [comment]
Closing this one, as this it not a new idea, just an oversight on my part.
