### ISSUE TITLE
roundhouse.lib on NuGet is compiled as x86 instead of Any CPU

### ISSUE THREAD

**Issue by JoeWirtley** [chucknorris/roundhouse#287]
I may be missing something, but it appears that the roundhouse.lib I get from the NuGet package (v0.8.8) is compiled for x86.  This pull request was closed implying it was already done:

https://github.com/chucknorris/roundhouse/pull/85

Am I missing something, or does some change need to be made to get an Any CPU dll?

**Comment by JoeWirtley** [comment]
Thanks!

**Comment by erikbra** [comment]
This one is Ok for 0.9.0 release, right, @BiggerNoise?

**Comment by BiggerNoise** [comment]
Yes
