### ISSUE TITLE
Move builds to AppVeyor?

### ISSUE THREAD

**Issue by jbogard** [chucknorris/roundhouse#288]
Have you folks considered moving to AppVeyor for builds? All my OSS projects are on it now. It gives me quite a bit more control etc. than the TeamCity CodeBetter one?

My life changed for the better once I moved onto it. You can also see people's appveyor.yml in their repos. It's free for OSS too :)

**Comment by ferventcoder** [comment]
@jbogard I have, and I've already been mentioning it to @erikbra and @BiggerNoise

**Comment by erikbra** [comment]
Do they have good build agents with new and shiny VS2017.4  tools, @jbogard?

**Comment by jbogard** [comment]
So you can install those in your startup script if you need to.

**Comment by erikbra** [comment]
So, now that #285 is merged, should we get the AppVeyor build to actually produce the proper outputs? Do we need to split in multiple pull requests? I see a couple of tasks:

1. Make sure roundhouse.nupkg is actually an artifact of the build
1. Fix that the rest of the nuget packages actually get produced too
1. How should we treat branching? Should we move to "proper" GitFlow (i.e. have a `develop` and a `master` branch?) `GitVersion.exe` kindof assumes this, so version numbers are better if we work like that 
(see [https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow/](https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow/))
1. If we move to using a develop and master branch, we can do more experimental work in the develop branch (forks off it), and release alpha/prerelease packages off that, to get user feedback before merging to master (`roundhouse-8.9.0-alpha.1.nupkg` or alike)
1. Set up an integration test environment? Or more? Is AppVeyor a good tool for running integration tests?
1. Other ideas? Maybe skip the integration test enviroment for now?

**Comment by BiggerNoise** [comment]
I would prioritize 1 & 2. However, I think that those would be dealt with in the UpperCakE effort that @ferventcoder wants to undertake. I do not expect that we will make RH releases until we can get that finished.

The inactivity of the past few years has driven off most of those that would be inclined to contribute, which has left us not really needing much of a branching model. I hope to see that trend reverse. I'm trying to think if gitflow would buy us much at our current level. I'm open to persuasion either way.

But, I can definitely skip the integration test environment for the moment.

**Comment by erikbra** [comment]
I think we could close this one, can't we, @BiggerNoise or @ferventcoder? If we need something to track the migration to Cake build, I think we should create another issue. Agree?

**Comment by BiggerNoise** [comment]
Agreed.
