### ISSUE TITLE
One unit-test takes tens of seconds (testing md5 algorithm)

### ISSUE THREAD

**Issue by erikbra** [chucknorris/roundhouse#289]
roundhouse.tests.cryptography.CryptographicServiceSpecs+when_using_an_unofficial_md5_implementation.should_have_parity_with_official_implementation
roundhouse.tests.dll **1 min 20 sec 424 ms**

I think that one can be modified - maybe not run as many iterations, maybe find some corner cases, and test them, or something. I don't think the unit test suite should be slowed down so much by one scenario :)

**Comment by BiggerNoise** [comment]
Yeah, that's nuts. I'm about to merge #285. I'll see if I can't make this a bit more reasonable right after.

**Comment by BiggerNoise** [comment]
Fixed by #290
