### ISSUE TITLE
[Enhancement] PostgreSQL Support

### ISSUE THREAD

**Issue by ferventcoder** [chucknorris/roundhouse#30]

**Comment by coderboy312** [comment]
Hello Can I get any guidance how I can configure my posgresql server in roundHouse.

**Comment by jswright91** [comment]
@coderboy312 Switch to Grate instead of RoundHouse.
Wiki: https://erikbra.github.io/grate/
Github: https://github.com/erikbra/grate

RoundHouse is no longer maintained.
