### ISSUE TITLE
Create 0.9.0 Release

### ISSUE THREAD

**Issue by BiggerNoise** [chucknorris/roundhouse#303]
This is where I am going to track my progress on getting the 0.9.0 release baked.

I tagged master with 0.9.0-pre which, if I understand all the new toys we have, will push a pre-release to NuGet.

If that works, then I assume that tagging with 0.9.0 would make the real release. 

Our conversations have been everywhere and a long weekend of too much food and too much goofing off have fuzzed my brain, so forgive me if I have it all wrong. 

Certainly, I should be able to grab the artifacts from the AppVeyor build and push those, but I thought this step was not needed.

**Comment by BiggerNoise** [comment]
OK. Build is done, but nothing on NuGet, so I have probably misunderstood wither what should happen or what I should have done to make it happen.

@erikbra - If you can confirm that I should manually post the artifacts from the AppVeyor build to NuGet, i'll do that tomorrow night.

**Comment by erikbra** [comment]
I'm sorry, I havent performed any integration with NuGet yet, I haven't got any credentials. I have only integrated with MyGet. So the publish to NuGet is still manual. Maybe @ferventcoder s Cake script will take care of this.

**Comment by BiggerNoise** [comment]
No worries on that. I just wanted to make sure that it wasn't expected to work automatically. I see what MyGet is doing for us now, so I can test the pre release and get the whole thing baked.

I should be able to wrap this up tomorrow night.

**Comment by BiggerNoise** [comment]
OK, Submitted to Chocolatey.
I was able to upload 0.9.0 to NuGet for the console and the MS Build tasks, but I cannot get the lib to upload. The issue is that the package name is 'RoundhousE' which is too similar to the id 'roundhouse' of the console package.

The library package should be named 'RoundhousE Library'. Unfortunately, I can't quite seem to figure out where we're getting the nuspecs from in the new build. I'm going to keep poking at it and I will update here if I am successful.

**Comment by BiggerNoise** [comment]
Got it.

**Comment by erikbra** [comment]
Great work. Happy you figured it out. I didn't think we would distribute anything but the console app via Chocolatey. Does it make sense to distribute the lib there as well?

**Comment by BiggerNoise** [comment]
Just the console to chocolatey.

All three packages go to NuGet; that's where the name collision occurred.

Huge thanks to you for getting this infrastructure work together.

**Comment by erikbra** [comment]
Aha, now I get it. But I see you found it. 
I hope the infra is working at least temporary, until we get the proper thing with Cake up and running. Hope the Chocolatey moderation is OK now too, and that it works for all DBs...

**Comment by BiggerNoise** [comment]
Still waiting on the Chocolatey moderation, but the release process itself was very smooth. The integration with MyGet makes preparing for the release stupid simple.
