### ISSUE TITLE
ETA on Update in Chocolatey?

### ISSUE THREAD

**Issue by eavonius** [chucknorris/roundhouse#304]
Just curious if there was any idea when we might see updated roundhouse packages in chocolatey.

The latest version up there is from 2013! It seems like there have been quite a few releases since then, though it's hard to tell if they are as stable.

Jayme

**Comment by BiggerNoise** [comment]
The lasts two releases did not go to Chocolatey because we had issues with moderation #274. As discussed in that issue, we expect that we should be able to address those issues in 0.9.0 which we are  currently in the process of releasing.
