### ISSUE TITLE
MySql DatabaseName not getting set when building connection string 

### ISSUE THREAD

**Issue by mmalik76** [chucknorris/roundhouse#313]
In MySqlDatabase build_connection_string method, the the database_name parameter is not being used when building the connection which causes an error generating the versioning tables.

**Comment by mmalik76** [comment]
Submitted pull request #314 to fix issue

**Comment by BiggerNoise** [comment]
Appreciate the report and the fix. I'd like to get a fix in for #312 to go with 0.9.2, but if I can't manage it sooner, then I'll release this by the end of the week.
