### ISSUE TITLE
CREATE ASSEMBLY problems

### ISSUE THREAD

**Issue by larsw** [chucknorris/roundhouse#321]
Hi,

 I'm trying to install a CLR assembly with a script in the roundhouse structure, but I'm having problems
 placing the file on disk / referencing it with a relative path in the statement, without getting a
 "CREATE ASSEMBLY failed because it could not open the physical file 'Xxx.dll': 3 ('The system cannot find the path specified')

 Anyone who can shed some light on where the file needs to be placed / how it can be referenced with a relative path?

**Comment by BiggerNoise** [comment]
@larsw  - I hope I didn't chase you away. Unfortunately, I don't know how to install a CLR assembly, I'm just trying to help you get to a roundhouse problem that I might be able to help you solve.

**Comment by larsw** [comment]
Hi again,

I created a workaround; I'm using BinaryFormatter (https://github.com/SqlQuantumLeap/BinaryFormatter) in combination with a pre- and post-script that I'm running with RH.

If I find some spare time, I'll look into extending RH to support it "natively"

**Comment by BiggerNoise** [comment]
I'm glad you were able to get it sorted out and thanks for leaving a link to your workaround.
