### ISSUE TITLE
Support SQL 2014 and 2016? 

### ISSUE THREAD

**Issue by johnxjcheng** [chucknorris/roundhouse#322]
When upgrading the databases that use RoundhouseE, we get this warning: 
Object RoundhousE.ScriptsRun.text_of_script uses deprecated data type TEXT, IMAGE or NTEXT which will be discontinued for future versions of SQL Server.

Any timeline to support the new SQL version?

**Comment by erikbra** [comment]
We could probably just change it to VARCHAR(MAX), but I don't know if that would break compatibility with older SQL Server versions. However, it _is_ only a warning that it might be removed in future versions, so there is no acute danger for it to stop working.

Are you experiencing any issues other than the warning?

**Comment by johnxjcheng** [comment]
No, there is no other warning. If the upgrade can be scheduled in the near future that will be great. Microsoft is stopping the support of SQL Server 2008 soon.

**Comment by BiggerNoise** [comment]
Just to be clear, when Microsoft stops supporting SQL Server 2008, that doesn't mean that TEXT is going away also.

But, it could at some point in the future and we should update our schema to accommodate this. Thank you for bringing it to our attention, I had no idea that they had deprecated the type. I'm sure that will be a popular decision with their users.

And curiosity question, I see that you're in Plano. Are you the John Cheng that works/worked for MedAssets (or whatever they're called these days)?

**Comment by johnxjcheng** [comment]
Hi, Andy. This is the John Cheng who worked with you before. Nice to meet you here! I understand the definition of deprecation and appreciate your consideration to address it in the future.

John Cheng

**Comment by BiggerNoise** [comment]
Good to see you also. 

We're trying to get a cross platform .NET core version of RH baked, so @erikbra and I are a bit busy at present, but I hope that we can address this shortly after.

**Comment by ferventcoder** [comment]
@BiggerNoise please fix the donation link to some location for you and @erikbra. You are doing amazing work, so make sure that goes to you - I forgot to remove it here when it stopped working over a year or so ago.

**Comment by LarsAndreasEk** [comment]
Hi, 

Any updated plans to change from TEXT to varchar(max) for columns?

Best regards
Lars Andreas
