### ISSUE TITLE
Publish RoundhousE as a dotnet global tool

### ISSUE THREAD

**Issue by erikbra** [chucknorris/roundhouse#332]
Literature:

https://natemcmaster.com/blog/2018/05/12/dotnet-global-tools/
https://github.com/natemcmaster/dotnet-globaltool-templates

Example of other global tool:

https://github.com/jerriep/dotnet-outdated

- This is dependent on the 1.0.0 release, _maybe_ it should be part of it? 
- Requires upgrade from .net core 2.0 to 2.1 (2.0 is not a long-term support release anyway=

Would enable being able to install RoundhousE (the .net core version - including multi-platform support, excluding some providers) with the following command, given that .net core is installed:

`dotnet tool install -g roundhouse`

And that's it...

Don't think this would be too much work.

**Comment by BiggerNoise** [comment]
I don't think the 2.1 is an issue at all.

If this isn't 1.0, then it should be in 1.0.1. I'm not sure we're going to have an ILMerge for core stuff, this seems like a somewhat better approach.

**Comment by erikbra** [comment]
Solved in PR #336

**Comment by BiggerNoise** [comment]
Merged

**Comment by mattiasnordqvist** [comment]
is this working, really?
