### ISSUE TITLE
SqlConnectionStringBuilder: use of Access Token

### ISSUE THREAD

**Issue by josho2** [chucknorris/roundhouse#344]
Not currently supporting all of the connection options for sqlconnectionstringbuilder.  I would like to be able to consume an access token with the connection string.  There is no way currently to instantiate the access token?  

Example:
server_connection.AccessToken = accessToken;
server_connection.Open();

**Comment by erikbra** [comment]
Thanks for reporting this, @josho2 . Is this the scenario you are describing? Just so I understand you correctly.

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication-configure#azure-ad-token

**Comment by garthbf** [comment]
yes that is correct. we would like to see an enhancement were we could pass in a token with the connection string and if present then have the code where you construct the connection string object also do:
connection.AccessToken = "Your JWT token"

**Comment by erikbra** [comment]
Yes, I see. We need a separate command line parameter for passing in the auth token, then, isn't that correct? Because if I understand it correctly, the authorization token is not part of the connection string.

**Comment by garthbf** [comment]
correct. it has to be a property set on the connection string object after it is create with the connection string string value.

**Comment by erikbra** [comment]
OK. Nothing to it but to do it, then ;)

Would you like to try creating a pull request? It's be best way of getting involved, and it's not an impossible task... :) I'll try to help you along the way as much as I can.
