### ISSUE TITLE
Build fail on Docker Linux container

### ISSUE THREAD

**Issue by GRXoft** [chucknorris/roundhouse#348]
This issue pertains to [release/1.0.0](https://github.com/chucknorris/roundhouse/tree/release/1.0.0) branch.

The project fails to build when run from a _Dockerfile_ while building _Linux_ container image. The error message reads:

> CSC : error CS1566: Error reading resource 'roundhouse.databases.sqlite.assemblyresource.System.Data.SQLite.dll' -- 'Could not find a part of the path '/root/.nuget/packages/System.Data.SQLite.Core/1.0.109.2/lib/net46/System.Data.SQLite.dll'.'

The issue seems to be caused by this entry in _./product/roundhouse.databases.sqlite/roundhouse.databases.sqlite.csproj_:

    <EmbeddedResource
      Include="$(NuGetPackageRoot)System.Data.SQLite.Core\1.0.109.2\lib\net46\System.Data.SQLite.dll">
        <Link>assemblyresource\System.Data.SQLite.dll</Link>
    </EmbeddedResource>

An ad-hoc solution that solves the compilation problem is to add a `Condition` attribute to the item so that it is referenced only when built against _net461_ target:

    <EmbeddedResource
      Include="$(NuGetPackageRoot)System.Data.SQLite.Core\1.0.109.2\lib\net46\System.Data.SQLite.dll" 
      Condition="'$(TargetFramework)' == 'net461'">
        <Link>assemblyresource\System.Data.SQLite.dll</Link>
    </EmbeddedResource>

I am not sure however how this affects other build scenarios.

**Comment by erikbra** [comment]
This looks like a bug, yes. I think we could replace `net461` with `$(TargetFramework)`, as I see there is a ` ~/.nuget/packages/system.data.sqlite.core/1.0.109.2/lib/netstandard2.0/` folder on my mac here. Do you have a Dockerfile you can share, to reproduce the issue, so that it's easier to see if the fix works, or, if you would like to try it, try replacing

```
<EmbeddedResource
  Include="$(NuGetPackageRoot)System.Data.SQLite.Core\1.0.109.2\lib\net46\System.Data.SQLite.dll">
    <Link>assemblyresource\System.Data.SQLite.dll</Link>
</EmbeddedResource>
```

with
```
<EmbeddedResource
  Include="$(NuGetPackageRoot)System.Data.SQLite.Core\1.0.109.2\lib\$(TargetFramework)\System.Data.SQLite.dll">
    <Link>assemblyresource\System.Data.SQLite.dll</Link>
</EmbeddedResource>
```

and send a Pull Request if it solves the issue.

**Comment by erikbra** [comment]
That said, I don't think you can expect the whole build to run on Linux. The "classic" rh.exe is ILMerged, and I haven't got that to run on my mac, at least. But the .net global tool one should end up in the `code_drop/packages` folder.

**Comment by GRXoft** [comment]
I actually only need to compile _/product/roundhouse.console/roundhouse.console.csproj_ to create a docker image with runnable _RoundhousE_. Here's my _Dockerfile_:

    FROM microsoft/dotnet:sdk as build-env
    ARG root="./product"
    WORKDIR /app/src/

    COPY ${root}/roundhouse/*.csproj roundhouse/
    COPY ${root}/roundhouse.console/*.csproj roundhouse.console/
    COPY ${root}/roundhouse.databases.access/*.csproj roundhouse.databases.access/
    COPY ${root}/roundhouse.databases.mysql/*.csproj roundhouse.databases.mysql/
    COPY ${root}/roundhouse.databases.oracle/*.csproj roundhouse.databases.oracle/
    COPY ${root}/roundhouse.databases.postgresql/*.csproj roundhouse.databases.postgresql/
    COPY ${root}/roundhouse.databases.sqlite/*.csproj roundhouse.databases.sqlite/
    COPY ${root}/roundhouse.databases.sqlserver/*.csproj roundhouse.databases.sqlserver/
    COPY ${root}/roundhouse.databases.sqlserver2000/*.csproj roundhouse.databases.sqlserver2000/
    COPY ${root}/roundhouse.databases.sqlserverce/*.csproj roundhouse.databases.sqlserverce/

    RUN dotnet restore roundhouse.console

    COPY ${root}/roundhouse roundhouse
    COPY ${root}/roundhouse.console roundhouse.console
    COPY ${root}/roundhouse.databases.mysql roundhouse.databases.mysql
    COPY ${root}/roundhouse.databases.postgresql roundhouse.databases.postgresql
    COPY ${root}/roundhouse.databases.sqlite roundhouse.databases.sqlite
    COPY ${root}/roundhouse.databases.sqlserver roundhouse.databases.sqlserver
    COPY ${root}/roundhouse.databases.sqlserver2000 roundhouse.databases.sqlserver2000
    COPY ${root}/roundhouse.databases.sqlserverce roundhouse.databases.sqlserverce

    RUN dotnet build roundhouse.console -f netcoreapp2.1 -c Release -o /app/bin --no-restore

The file lives in the root directory of the repository. I've tried your suggestion, and it didn't work - or at least not entirely. The thing is that when run in _microsoft/dotnet:sdk_ (which currently is equivalent to _microsoft/dotnet:2.1-sdk_), the `dotnet restore` command puts the file in question at _/root/.nuget/packages/system.data.sqlite.core/1.0.109.2/lib/netstandard2.0/System.Data.SQLite.dll_ (the file name seems to be preserved, but the package folder name is a lower-cased version of the package name). And in that particular environment, since file-system paths are case-sensitive, it should also be reflected in _.csproj_:

    <EmbeddedResource
      Include="$(NuGetPackageRoot)system.data.sqlite.core\1.0.109.2\lib\$(TargetFramework)\System.Data.SQLite.dll">
        <Link>assemblyresource\System.Data.SQLite.dll</Link>
    </EmbeddedResource>

I have confirmed that it solves the problem for _Docker_ build I've described, and also seems not to brake _Windows_ build, although for the latter I only ran a simple _Visual Studio_ solution build rather than any of the build tools provided. I don't have any means to test this on _MAC_ though.

**Comment by erikbra** [comment]
We should work on an official docker release of RoundhousE, but just for now, the 1.0.0 rc is now live on NuGet, so you should be able to replace all the compilation and stuff in your Dockerfile with the following (you need to specify the version because it's pre-release):

```
dotnet tool install --global dotnet-roundhouse --version 1.0.0-rc.2
```

**Comment by GRXoft** [comment]
I definitely would if I could, but there are some customizations to _RoundhousE_ code that need to be incorporated in the _Docker_ image, so that's not an option. Anyway, the fix I mentioned in my previous comment got me going, so perhaps it's more of a workaround for those in similar situation, than a bug fix worthy of merging into the official branch.
