### ISSUE TITLE
Is it possible to remove RoundHousE_ScriptsRun text_of_script column?

### ISSUE THREAD

**Issue by ido-ran** [chucknorris/roundhouse#354]
I'm working on a project that uses RoundHousE migrations. We accumulated lots of migrations over a 3 years period.
I've done an analysis on our database and found that RoundHousE_ScriptsRun is our 2nd largest table and it takes 72MB on disk. When I removed `text_of_script` column the table dropped to 160KB on disk.

Is it possible to remove that column?

We don't need the full script text in the database. We have the files in source control.

**Comment by erikbra** [comment]
Of course, this could be an option. It depends on what people want. I don't use the RoundhousE tables much myself, for selects and stuff, but other people's mileage may vary. I think removing the column could break others' use of the tables, but, technically, only the hash is needed for RoundhousE to work correctly, if I'm not mistaken.

Anyone else out there with opinions? I won't go ahead and remove the column before gathering mor opinions. I see your concern, but people might be using it. We could, of course, make it an option. But, ironically enough, versioning of the Roundhouse.* tables are a weak point in RoundhousE, so changes are not so easily made either.

That said, 72MB isn't exactly a huge database table. People have tens and hundreds of GBs in their databases, but, of course, people have different sizes and different applications.

**Comment by ido-ran** [comment]
Any update on this issue?

**Comment by erikbra** [comment]
Sorry for the long lead-time. PR #389 should solve this once resolved.
