### ISSUE TITLE
ReliableSqlConnection holds connections open

### ISSUE THREAD

**Issue by BlythMeister** [chucknorris/roundhouse#368]
The ReliableSqlConnection will never close the connection...even when it should.

**Comment by BlythMeister** [comment]
i am working on a PR to fix this.

**Comment by BlythMeister** [comment]
This was my bad, nothing to see here....

**Comment by erikbra** [comment]
OK, so you actually meant to abandon the PR?

**Comment by BlythMeister** [comment]
Yeah, I misread the code...it was something else holding connection in my code 🤣

**Comment by erikbra** [comment]
It happens. A lot. To everyone ;)
