### ISSUE TITLE
rh.deps.json error when installing with dotnet tool

### ISSUE THREAD

**Issue by yolofy** [chucknorris/roundhouse#373]
After installing with
`dotnet tool install -g dotnet-roundhouse --ignore-failed-sources`
and running
`rh`
i get
`Error:
  An assembly specified in the application dependencies manifest (rh.deps.json) was not found:
    package: 'roundhouse.databases.mysql', version: '1.0.0'
    path: 'roundhouse.databases.mysql.dll'
`

**Comment by jacobscunn07** [comment]
I ran the same command (minus the ignore failed sources flag) and got that error. I then ran `cinst roundhouse` in a terminal with elevated privileges and all worked for me. 

It may have been the fact that I didn't run the command that you mentioned in a terminal with elevated privileges that caused things to go wrong. 🤷‍♂️

**Comment by yolofy** [comment]
No, there is a dll missing in the package. I don't have chocolatey available at the target machine.

**Comment by fuzzyllama** [comment]
This bug was introduced somewhere in 1.0.4.  Building docker with -"-version 1.0.3" does not present the issue

**Comment by erikbra** [comment]
The chocolatey install and the dotnet tool install are two different builds altogether. The first is a full framework build (net461), and the latter is a netcore2.1 build. I have had this problem before, if building on one box an using on another. I think it's related to exact versions of .net sdk installed on the target vs build machines.

A drawback with dotnet tool install is that it requires the whole .net sdk to be installed, not just the runtime. Maybe not a problem for a lot of people, but e.g. the docker image could be much slimmer if not dependent on the sdk. I'll look into this issue specifically, with the missing dll. Could you please run
 
`dotnet --list-runtimes`

and

`dotnet --list-sdks`

on the box where you have the problem?

thanks a lot.

**Comment by erikbra** [comment]
@yolofy - I've just released v 1.1.0 of RoundhousE, could you please confirm that you don't have this issue anymore with this release? I haven't been able to reproduce the issue anymore with this version.

**Comment by erikbra** [comment]
Closing this - I think the bug is fixed. Please come back if you still see this error.
