### ISSUE TITLE
Forgot to upload roundhouse.sqlserverce to Nuget.org

### ISSUE THREAD

**Issue by BlythMeister** [chucknorris/roundhouse#380]
The latest release of 1.1.0 has all packages in Nuget.org except 1...roundhouse.sqlserverce
https://www.nuget.org/packages/roundhouse.sqlserverce/ shows a 404.

Good news is, the release has got the nuget package in it...but should be in nuget really :)

**Comment by erikbra** [comment]
Ooops. Thank you very much. I had forgot about that one :)

Now it's up (or when the nuget.org indexers are done processing).

https://www.nuget.org/packages/roundhouse.sqlserverce

**Comment by BlythMeister** [comment]
As it turns out...we realised we only need roundhouse.sqlserver...but we did have roundhouse.lib which alerted us to the mistake 🤣

**Comment by erikbra** [comment]
Well, it wasn't good for nothing, then ;)
That was the thought of splitting it, too. I think not many need all DB providers at all, most only need one. And it makes it easier moving some of the packages forward (to e.g. .netstandard or .netcore3.0), while keeping some (e.g. Oracle) on older frameworks (4.6, e.g), without them keeping the other ones back.
