### ISSUE TITLE
Migrate <iconUrl> to embedded <icon> in nupkg

### ISSUE THREAD

**Issue by erikbra** [chucknorris/roundhouse#391]
iconUrl is deprecated

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packageiconurl

![image](https://user-images.githubusercontent.com/1628994/66779644-f99cfe80-eece-11e9-8374-1ba075cb78aa.png)

**Comment by erikbra** [comment]
Solved in #412

**Comment by ferventcoder** [comment]
That will not allow you to submit to chocolatey.org anymore. Guessing you are building nuget and chocolatey separately?
