### ISSUE TITLE
can dotnet-roundhouse.1.2.0 be included in .NET Core 2.2.0 app ?

### ISSUE THREAD

**Issue by jgrandydev** [chucknorris/roundhouse#396]
I have a .NET Core 2.20 Visual Studio solution .sln that includes a RoundHouse.1.1.0 project .csproj 

When built locally the package folder is created as expected at : 

/SolutionFolder/RoundHouse/packages/roundhouse/1.1.0/

However when built in TeamCity with the .NET CLI restore build step this folder is not added and so rh.exe is not available.

I've tried adding a PackageReference to my .NET Core 2.2.0 project but apparently Visual Studio doesn't like mixing Framework at .NET Core libs because it hangs.

Will dotnet-roundhouse.1.2.0 solve this problem ?

Exactly what should I do ?

**Comment by erikbra** [comment]
Sorry for the long delay here. If you want to include RoundhousE in another app, I would not recommend using dotnet-roundhouse, as this is a .net core global tool, and intended for separate execution. 

Please see https://github.com/chucknorris/roundhouse#dotnet-core-global-tool-windows-linux-macos-etc

For including in another app/library, please use e. g. the roundhouse nuget package.

What exactly are you trying to achieve? Understanding what you are trying to achieve makes it easier to answer the question

**Comment by erikbra** [comment]
Closing due to lack of response
