### ISSUE TITLE
NuGet restoring roundhouse package to slightly different folder structures

### ISSUE THREAD

**Issue by jgrandydev** [chucknorris/roundhouse#398]
Visual Studio 2019

Sometimes NuGet restores my package to this folder structure :

`\packages\roundhouse.1.1.0\roundhouse.1.1.0.nupkg`

but sometimes to this folder structure :

`\packages\roundhouse\1.1.0\roundhouse.1.1.0.nupkg`

Notice the slight difference.

I can't find any config setting that controls which folder-structure is used.

Does anyone know ?

Could this be related to how the roundhouse package is created ?

**Comment by erikbra** [comment]
This changed some time in NuGet history (depending on the NuGet version), I think. 

If you need to know the exact location, I would recommend specifying a specific location when running nuget restore or install. 

https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-nuget-cli#install-a-package
