### ISSUE TITLE
text_of_script missing special characters, converting to question marks when entered into SQL Server DB

### ISSUE THREAD

**Issue by bpercy11** [chucknorris/roundhouse#404]
Consider a script in the runBeforeUp folder that contains a string that holds a special character, like the ohm symbol (Ω). After roundhouse executes this script and upon insertion of the script contents into the the [RoundhousE].[ScriptsRun].[text_of_script] column, the ohm symbol is dropping information (bytes) associated with it and is then being entered as a question mark (?).

This could possibly be due to the text_of_script column being of type text instead of nvarchar. I have not located in the roundhouse src code exactly where this problem could be alleviated just yet.

**Comment by erikbra** [comment]
Thank you for reporting.

A couple of questions:
1. Which encoding is the text file stored in? UTF-8 or something else?
1. Which database are you connecting to?
1. Do you have a simple repro that demonstrates the problem?

**Comment by erikbra** [comment]
@bpercy11 do you have anything more to add to this issue? If not, I will have to close it.

**Comment by erikbra** [comment]
Closing due to lack of response.
