### ISSUE TITLE
How should I handle transactions in a good way?

### ISSUE THREAD

**Issue by jden123** [chucknorris/roundhouse#405]
Hello!

I have an `up` script that cleans up two tables and if the script fails the changes are to be rolled back. So, the queries should be run in a transaction.

Does RH handle this case? Could you please clarify if RH rolls back it automatically or I should deal with it manually. 

Could you please clarify `-t` param?

**Comment by alexpantyukhin** [comment]
Up this issue! I'm interesting in `rollaback` on fail functionality also.

**Comment by erikbra** [comment]
This should work, yes. That is what the `-t` parameter does. It is dependent on the database supporting it, though, but RoundhousE  should issue a warning if the database provider does not support transactions.

I would recommend trying it, to be sure. Setting up a test case as you describe, shouldn't be too difficult.
