### ISSUE TITLE
build.bat does not work well

### ISSUE THREAD

**Issue by qaswd** [chucknorris/roundhouse#407]
I've tried to build the solution using the build.bat but no luck. There is the log files:

[build.log](https://github.com/chucknorris/roundhouse/files/4818614/build.log)
[ilmerge.log](https://github.com/chucknorris/roundhouse/files/4818615/ilmerge.log)

**Comment by erikbra** [comment]
Hi, no, sorry, build.bat does not work well ATM. Please use build.ps1 instead (in Powershell).

**Comment by qaswd** [comment]
ok, thanks
