### ISSUE TITLE
RH doesn't work for .NET 3.1

### ISSUE THREAD

**Issue by marrcow** [chucknorris/roundhouse#413]
Hi,

I've got the following error when running  **rh** command:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.5 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.14-x64

```

I tried on mcr.microsoft.com/dotnet/core/sdk:3.1 docker image.

In the requirements, we can read: ".NET Core 2.1+ (for the dotnet core distribution)", which means it should work with any newer than 2.1

Cheers,
marrcow

**Comment by neoaisac** [comment]
Same
Dockerfile example:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

RUN dotnet tool install -g dotnet-roundhouse
RUN /root/.dotnet/tools/rh
```

**Comment by majkel89** [comment]
try

```
FROM mcr.microsoft.com/dotnet/core/sdk:2.1

RUN dotnet tool install -g dotnet-roundhouse
RUN /root/.dotnet/tools/rh
```

**Comment by erikbra** [comment]
There is already a docker image for RoundhousE, is there a reason you cannot run on that one, or build upon it?

I'm tempted to delay this, as I plan on migrating to .net 5 when it goes GA, and try out single-file publish, so that it would be framework independent.

**Comment by cbordemanSPS** [comment]
This was a year ago and .Net Core 2.1 LTS ends in just a few weeks.  What is the hold up?  People really need this!

**Comment by erikbra** [comment]
Terribly, terribly sorry for the lack of response here. I don't really have the time available to do as much as I want with RoundhousE. The beauty of Open Source, is, however, that id you have the time to look into the problem, and suggest a solution, you can submit a pull request, and get it merged.

That said, there is a lot of technical debt in RoundhousE, and a lot of old dependencies that makes moving forward on newer .NET versions cumbersome. There are probably some of the dependencies that are compiled against .NET Framework 2.1.

**Comment by erikbra** [comment]
Solved in https://github.com/chucknorris/roundhouse/releases/tag/1.3.0
