### ISSUE TITLE
Latest docker image seems to have an issue with arguments

### ISSUE THREAD

**Issue by bizzzd** [chucknorris/roundhouse#414]
The latest dotnetroundhouse/roundhouse docker image always responds with an error regarding missing database or connection string argument:

![image](https://user-images.githubusercontent.com/37587047/87934473-cc9dfd80-ca97-11ea-8a46-b7a26a447351.png)

The version 1.0.2 seems to be working correctly.

I tried different ways to specify connection string (-c, --cs, --connectionstring) - all give the same error above

**Comment by erikbra** [comment]
Thanks a lot for your contribution, and sorry for the long delay in merging.

**Comment by erikbra** [comment]
The docker image 1.2.3 is now up on docker hub, @bizzzd
