### ISSUE TITLE
Nuget tool version 1.2.3 fails to install (DotnetToolSettings.xml missing)

### ISSUE THREAD

**Issue by Cultti** [chucknorris/roundhouse#421]
When installing latest version 1.2.3 with command `dotnet tool install -g dotnet-roundhouse` it fails:
```
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'dotnet-roundhouse' failed to install. Contact the tool author for assistance.
```

Latest working version is 1.2.1 and it installs without any errors `dotnet tool install -g dotnet-roundhouse --version 1.2.1`

**Comment by erikbra** [comment]
OH, yes, you are right. This needs looking in to. Thanks for reporting!

**Comment by Chris3773** [comment]
Is anyone able to create a PR to fix this issue?

**Comment by docrinehart** [comment]
Can confirm that 1.2.1 also works for dotnet local tool (dotnet > 3.x), but 1.2.3 gives the same error on attempted installation

```
dotnet tool install dotnet-roundhouse --version 1.2.1
```

**Comment by kieranbenton** [comment]
Just discovered this issue as well - keeps tripping us up as we onboard people.

**Comment by erikbra** [comment]
Solved in https://github.com/chucknorris/roundhouse/releases/tag/1.3.0

**Comment by erikbra** [comment]
Terribly sorry for the lack of feedback here, time is a precious resource, but you shouldn't need to wait this long when you actually take the time to create a PR. Could you please confirm that 1.3.0 works for you as well?

**Comment by Cultti** [comment]
Thanks, @erikbra! The issue has been resolved :)

**Comment by erikbra** [comment]
Lovely. And sorry for the delay
