### ISSUE TITLE
Dotnet core global tool installer don't work

### ISSUE THREAD

**Issue by henningandersson** [chucknorris/roundhouse#430]
When I'll try to install Roundhouse with `dotnet tool install -g dotnet-roundhouse` i get an error:

```
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'dotnet-roundhouse' failed to install. Contact the tool author for assistance.
```
It seems there is some mishap. Fast fix for me was to use other install method, but the install should be working or otherwise be removed from the manual.

Seems like a nifty tool otherwise!

**Comment by zzdtri** [comment]
1.2.1 seems to work: `dotnet tool install -g dotnet-roundhouse --version 1.2.1`

**Comment by kimjamia** [comment]
This looks like a duplicate of #421.

**Comment by erikbra** [comment]
Solved in https://github.com/chucknorris/roundhouse/releases/tag/1.3.0
