### ISSUE TITLE
Latest images in dockerhub do not have correct `ENTRYPOINT`

### ISSUE THREAD

**Issue by tkent** [chucknorris/roundhouse#432]
The Dockerfile `ENTRYPOINT` for the `latest` tag (also `1.2.3`) does not have the current `ENTRYPOINT` defined in this repo. Instead, the `ENTRYPOINT` is defined as:

```
 ENTRYPOINT ["/bin/sh" "-c" "dotnet rh.dll"]
```

([see here](https://hub.docker.com/layers/dotnetroundhouse/roundhouse/1.2.3/images/sha256-854467d4535d80a2cb929607427458f9bcabff6585e04570a9c5ce50b0c4655d?context=explore))

This results in the official image being unable to process arguments if the `ENTRYPOINT` is not overwritten.

### Step to reproduce:

Running the below command will not show the help message, but rather a message that connection string was not provided.

```
docker run --rm dotnetroundhouse/roundhouse:1.2.3  --help
```

Running the command below, with the entrypoint overwritten, will correctly show the help message.

```
docker run --rm --entrypoint="dotnet" dotnetroundhouse/roundhouse:1.2.3  rh.dll --help
```

**Comment by erikbra** [comment]
Solved in https://github.com/chucknorris/roundhouse/releases/tag/1.3.0

New images:

docker pull dotnetroundhouse/roundhouse:latest
docker pull dotnetroundhouse/roundhouse:1.3.0
