### ISSUE TITLE
Can logging to the migrations folder be disabled?

### ISSUE THREAD

**Issue by macfarmw** [chucknorris/roundhouse#435]
I have a case where the path for some of the files Roundhouse is trying to save to the migrations folder lead to path too long error. This is caused by a long AWS RDS fully qualified server name. I don't really need the migrations output and I would like to disable this option if that's possible.

Is there a way to disable this logging function when I call rh.exe?

Thanks.

**Comment by erikbra** [comment]
Yes, the `--disableoutput` switch should do this, please see https://github.com/chucknorris/roundhouse/wiki/ConfigurationOptions#switches

You can also choose a different output folder with the `--outputpath` option.
