### ISSUE TITLE
Running RH without access to master database

### ISSUE THREAD

**Issue by kimjamia** [chucknorris/roundhouse#442]
It would be really nice to have an option that prevents RH from trying to connect to the `master` database.

In Azure SQL Database, a [user can run](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql?view=azuresqldb-current&tabs=sqlpool#permissions-1) `ALTER DATABASE` commands if the user is a `db_owner` of the database. The user can be a contained database-authenticated user. The user doesn't need to be a master-database-authenticated login.

I worked around this by setting the `--csa` option to point to the same database but I'm not sure if that might cause some issues.

**Comment by erikbra** [comment]
Hi, @kimjamia . This shouldn't be a problem, I am pretty sure that it should not try to connect to the admin database if you specify the `--dnc`, aka `--donotcreate` switch. I have been using this specifically against Azure for that particular reason (see https://github.com/chucknorris/roundhouse/wiki/ConfigurationOptions#switches)

That said, please be aware that no one is actively maintaining RoundhousE at the moment, that I know of. I have called bankruptcy on the code, and started over, with `grate`, see #438 .
