### ISSUE TITLE
Option to have PRINT output show up in logs

### ISSUE THREAD

**Issue by Jaykul** [chucknorris/roundhouse#68]
A lot of scripts have debugging-style PRINT statements in them (e.g. usp_GetDate.sql and 003_AppPermissionsWiring.sql from the sample). We need an option to have the output of those PRINT statements show up in console/log output when they're run by RoundhousE.

At least in SQL and Oracle it should just be a matter of handling the InfoMessage event on the connection (it's not on the base class, and I don't know anything about your other databases...) http://www.dotnetcurry.com/ShowArticle.aspx?ID=344

**Comment by jzabroski** [comment]
This is great, but what we really need bubbling back to the logger are all User Error Message events.  Some of these get swallowed right now.

I would break the debug flag into multiple levels.  That's what most *NIX utilities do.

**Comment by ferventcoder** [comment]
@jzabroski Do you want to add a new ticket? I don't think we realized that some get swallowed. Definitely not what we want to happen.
