### ISSUE TITLE
Idea/Suggestion: Exclude Switches

### ISSUE THREAD

**Issue by ssuther** [chucknorris/roundhouse#77]
We use two distinct deployment mechanisms:.

1) During a normal database 'upgrade' deployment we drop all objects (sprocs/views/functions etc through alterDatabase script) and then force RoundhousE to add them.  This is working wonderfully.

2) We also a need to do a 'fresh' database deployment to new environments using RoundhousE.  

As part of our weekly build, we carry out an 'upgrade' of our blank master and back it up.  This is then placed into the RoundhousE folder structure.  This backup is fully up-to-date and requires a simple 'post-restore' script running over it and potentially an environmental specific script.  

As it is by design, after the database is restored in, it proceeds to continue in normal mode (as it is intended).  In this circumstance it drops everything etc, all of which is both unnecessary and time consuming.

It would be highly beneficial for us, and potentially others, for the ability to exclude certain script types or folders (all to be included by default, unless overridden by this switch.

**Comment by BiggerNoise** [comment]
Closing
