### ISSUE TITLE
Query/Idea: RoundHouse tables created after migration

### ISSUE THREAD

**Issue by dilipms** [chucknorris/roundhouse#88]
Roundhouse tables - ScriptsRun, ScriptsRunErrors and Version are created on the same database. 

Well, just being wondered if it is possible to have these tables in a different database?
Intention is to keep the structure of the database intact :)

**Comment by BiggerNoise** [comment]
Closing due to age and lack of P/R. Please open a new issue if you'd like us to reconsider.
